api_platform:
    title: 'Hotel REST'

    # The description of the API.
    description: 'Hotel API'

    # The version of the API.
    version: '1.0.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false
    
